#!/bin/bash
echo "[" > $1
FOUND_ANY=false
for i in "${@:2}"; do
	if [ -f "$i" ]; then
		cat "$i" >> $1
		FOUND_ANY=true
	fi
done
if [ "$FOUND_ANY" == "true" ]; then
	truncate -s -2 $1
fi
echo "]" >> $1
