-- SPDX-License-Identifier: MIT
-- SPDX-FileContributor: Adrian "asie" Siekierka, 2023

local path = require('pl.path')
local tablex = require('pl.tablex')
local utils = require('pl.utils')
local toml = require('toml')
local wfmath = require('wf.internal.math')
local wfoverlaylist = require('wf.internal.overlay_list')
local wfpath = require('wf.internal.path')
local wfutil = require('wf.internal.util')
local wswan = require('wf.internal.platform.wswan')

local tool_fix = require('wf.internal.tool.gbatool.fix')

local function romlink_call_linker(linkscript_filename, output_elf, output_file, linker_args)
    local success, code = execute_verbose(
        wfpath.executable('arm-none-eabi-gcc', 'toolchain/gcc-arm-none-eabi'),
        table.pack("-T", linkscript_filename, "-o", output_elf, table.unpack(linker_args))
    )
    if not success then
        error('ld exited with error code: ' .. code)
    end

    local success, code = execute_verbose(
        wfpath.executable('arm-none-eabi-objcopy', 'toolchain/gcc-arm-none-eabi'),
        table.pack("-O", "binary", output_elf, output_file)
    )
    if not success then
        error('objcopy exited with error code: ' .. code)
    end
end

local function rom_write_linkscript(f, parent_name, config)
    f:write([[
/* automatically generated by wf-gbatool on ]] .. os.date() .. [[ */
INCLUDE ]] .. parent_name .. [[

SECTIONS {
]])

    if config.overlays ~= nil and config.overlays.iwram ~= nil then
        local layers = wfoverlaylist.create(config.overlays.iwram)
        local prev_layer = nil
        for layer_i, layer in ipairs(layers) do
            if prev_layer == nil then
                f:write(string.format("  __overlay_iwram%d_start = ADDR(.bss.iwram) + SIZEOF(.bss.iwram);\n", layer_i))
            else
                prev_layer_expr = "0"
                for _, node in pairs(prev_layer) do
                    if not node.terminating then
                        prev_layer_expr = string.format("MAX(SIZEOF(.iwram_%s), %s)", node.name, prev_layer_expr)
                    end
                end
                f:write(string.format("  __overlay_iwram%d_start = __overlay_iwram%d_start + %s;\n", layer_i, layer_i - 1, prev_layer_expr))
            end
            for _, node in pairs(layer) do
                f:write(string.format("  __load_addr_iwram_%s = __overlay_iwram%d_start;\n", node.name, layer_i))
            end
            f:write(string.format("  OVERLAY __overlay_iwram%d_start : NOCROSSREFS {\n", layer_i))
            for _, node in pairs(layer) do
                f:write(string.format("    .iwram_%s {\n", node.name))
                f:write(string.format("      *(SORT(.iwram_%s.sorted.*))\n", node.name))
                f:write(string.format("      *(.iwram_%s .iwram_%s.*)\n", node.name, node.name))
                f:write(string.format("      . = ALIGN(. != 0 ? 4 : 1);\n"))
                f:write(string.format("    }\n"))
            end
            f:write(string.format("  } >IWRAM AT>ROM :IWRAM\n"))
            prev_layer = layer
        end
    end

f:write([[}
]])
end

local function romlink_run(args, linker_args)
    local config = toml.decodeFromFile(args.config or "wfconfig.toml")
    local parent_filename = "link-rom.ld"
    if args.subtarget == "multiboot" then
        parent_filename = "link-multiboot.ld"
    end

    -- generate linkscript
    local linkscript_filename = args.script
    if linkscript_filename == nil then
        linkscript_filename = temp_dir:path("link.ld")
        local linkscript_file = io.open(linkscript_filename, "w")
        rom_write_linkscript(linkscript_file, parent_filename, config)
        linkscript_file:close()
    end

    -- run "arm-none-eabi-ld", "arm-none-eabi-objcopy"
    romlink_call_linker(linkscript_filename, args.output_elf or temp_dir:path("a.out.elf"), args.output, linker_args)

    -- run "wf-gbatool fix"
    local tool_fix_args = tablex.copy(args)
    tool_fix_args.input_file = args.output
    local tool_fix_success, tool_fix_error = pcall(function()
        tool_fix.run(tool_fix_args)
    end)
    if not tool_fix_success then
        os.remove(args.output)
        error(tool_fix_error)
    end
end

return {
    ["arguments"] = [[
[args...] -- <linker args...>: link a GBA target ROM
  -c,--config   (optional string)  Configuration file name;
                                   wfconfig.toml is used by default.
  -o,--output   (string)           Output ROM file name.
  --output-elf  (optional string)  Output ELF file name;
                                   only stored on request.
  -T,--script   (optional string)  Custom link script to use.
                                   This disables generated link script
                                   functionality.
  -v,--verbose                     Enable verbose logging.
  <subtarget>   (string)           Subtarget: "rom" or "multiboot".
]],
    ["argument_separator"] = "--",
    ["description"] = "link a GBA target ROM",
    ["run"] = romlink_run
}
